version: '3.8'
services:
  steel:
    build: .
    image: steel
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - ./output:/app/output
      - ./src/ai/weights:/app/src/ai/weights
      - ./sample:/app/sample
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PYTHONPATH=/app/src
    ports:
      - "5001:5001"
    env_file: .env

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5671:5671"
      - "15671:15671"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5